
services:
  db:
    image: mysql:8.0
    container_name: redsocialWORKCAST-mysql
    environment:
      MYSQL_ROOT_PASSWORD: 1234567890
      MYSQL_DATABASE: RedSocial
      MYSQL_USER: DBA
      MYSQL_PASSWORD: 1234
    ports:
      - "3308:3306"
    volumes:
      - mysql_data:/home/yanina/ProyectoSop/Docker
    networks:
      - monitoring_net

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - monitoring_net
    healthcheck:
     test: ["CMD", "wget", "--spider", "http://localhost:9090/-/ready"]
     interval: 30s
     timeout: 10s
     retries: 3

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin_password
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    networks:
      - monitoring_net



volumes:
  mysql_data:

networks:
  monitoring_net:
    driver: bridge
